version: '3.9'

services:
    nest-api:
        container_name: nest-api
        build:
            context: .
            target: production
        ports:
            - 3000:3000
        env_file:
            - .env
